FROM python:3.12-slim

#can add extra stuff later if needed
RUN pip install --no-cache-dir fastapi uvicorn

COPY src/utils/executor_server.py /executor_server.py

CMD ["python", "/executor_server.py"]