services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./src/.env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:18.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./src/.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  postgres_data: