services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./src/.env
    networks:
      - gvnai-backend
      - gvnai-sandbox
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:18.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./src/.env
    ports:
      - "5432:5432"
    networks:
      - gvnai-backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  gvnai-backend:
    name: gvnai-backend
    driver: bridge

  gvnai-sandbox:
    name: gvnai-sandbox
    driver: bridge
    internal: true

volumes:
  postgres_data:
